# windows_opacity = 1.0

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[colors]
# draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 400
blink_timeout = 0
unfocused_hollow = true

[cursor.style]
blinking = "Never"
# shape = "Underline"

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 20

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[font.bold_italic]
style = "Bold Italic"

# [font.glyph_offset]
# x = 0
# y = 0

# [font.offset]
# x = 0
# y = 0

[[keyboard.bindings]]
action = "Paste"
key = "Paste"

[[keyboard.bindings]]
action = "Copy"
key = "Copy"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mode = "~Vi"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Control"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 2500
multiplier = 3

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
startup_mode = "Windowed"

[window.dimensions]
columns = 80
lines = 24

[general]
live_config_reload = true
import = ["/home/mmrza/.config/alacritty/rose-pine.toml"]
